version: '3'

services:
  pgsql:
    build:
      context: ./pgsql
    container_name: socialnet_pgsql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - local

  mainapp:
    build:
      context: service
    container_name: socialnet_app
    depends_on:
      pgsql:
        condition: service_healthy
    restart: always
    tty: true
    stdin_open: true
    ports:
      - "8800:8800"
    networks:
      - local
    environment:
      - SOCIALNET_DB=snet
      - SOCIALNET_DB_PASS=socialnet
      - SOCIALNET_DB_USER=socialnet
      - SOCIALNET_DB_PORT=5432
      - SOCIALNET_DB_TYPE=pgsql
      - SOCIALNET_DB_ADDRESS=socialnet_pgsql

  dialogapp:
    build:
      context: dialog
    container_name: socialnet_dialog
    depends_on:
      pgsql:
        condition: service_healthy
    restart: always
    tty: true
    stdin_open: true
    ports:
      - "8801:8801"
    networks:
      - local
    environment:
      - DIALOG_DB_TYPE=pgsql
      - DIALOG_DB_PORT=5432
      - DIALOG_DB_ADDRESS=socialnet_pgsql
      - DIALOG_DB=snet_dialog
      - DIALOG_DB_PASS=socialnet
      - DIALOG_DB_USER=socialnet


networks:
  local: