version: "3.9"

services:
  postgres:
    container_name: postgres01
    image: postgres
    # ports:
    #   - 5432:5432
    expose:
      - 5432
    volumes:
      - ./postgres01/:/var/lib/postgresql/data
      - ./full-dump/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: pass
      # POSTGRES_DB: snet
   
    networks:
      - snet  

  postgres-exporter:
    container_name: postgres-exporter01
    image: prometheuscommunity/postgres-exporter
    # ports:
    #   - 9187:9187
    expose:
      - 9167
    environment:
      DATA_SOURCE_NAME: "postgresql://socialnet:socialnet@postgres01:5432/snet?sslmode=disable&Timezone=UTC"
    networks:
      - snet  

networks:
  snet:
      name: socialnet
      external: true
